# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\x12\x07\x62\x61\x63kend\"3\n\x0e\x42\x61\x63kendRequest\x12\x11\n\tsql_query\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"!\n\x0f\x42\x61\x63kendResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2Q\n\x0e\x42\x61\x63kendService\x12?\n\nExecuteSQL\x12\x17.backend.BackendRequest\x1a\x18.backend.BackendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKENDREQUEST']._serialized_start=26
  _globals['_BACKENDREQUEST']._serialized_end=77
  _globals['_BACKENDRESPONSE']._serialized_start=79
  _globals['_BACKENDRESPONSE']._serialized_end=112
  _globals['_BACKENDSERVICE']._serialized_start=114
  _globals['_BACKENDSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
