# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"$\n\x0eGatewayRequest\x12\x12\n\njson_query\x18\x01 \x01(\t\"#\n\x0fGatewayResponse\x12\x10\n\x08response\x18\x01 \x01(\t2S\n\x0eGatewayService\x12\x41\n\x0cProcessQuery\x12\x17.gateway.GatewayRequest\x1a\x18.gateway.GatewayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEWAYREQUEST']._serialized_start=26
  _globals['_GATEWAYREQUEST']._serialized_end=62
  _globals['_GATEWAYRESPONSE']._serialized_start=64
  _globals['_GATEWAYRESPONSE']._serialized_end=99
  _globals['_GATEWAYSERVICE']._serialized_start=101
  _globals['_GATEWAYSERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
