# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_balancer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13load_balancer.proto\x12\rload_balancer\"\x1b\n\x0c\x43\x61\x63heRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"-\n\rCacheResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"P\n\x0f\x43\x61\x63heSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x03 \x01(\t\x12\x11\n\toperation\x18\x04 \x01(\t\"#\n\x10\x43\x61\x63heSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb0\x01\n\x0c\x43\x61\x63heService\x12L\n\rGetCachedData\x12\x1b.load_balancer.CacheRequest\x1a\x1c.load_balancer.CacheResponse\"\x00\x12R\n\rSetCachedData\x12\x1e.load_balancer.CacheSetRequest\x1a\x1f.load_balancer.CacheSetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CACHEREQUEST']._serialized_start=38
  _globals['_CACHEREQUEST']._serialized_end=65
  _globals['_CACHERESPONSE']._serialized_start=67
  _globals['_CACHERESPONSE']._serialized_end=112
  _globals['_CACHESETREQUEST']._serialized_start=114
  _globals['_CACHESETREQUEST']._serialized_end=194
  _globals['_CACHESETRESPONSE']._serialized_start=196
  _globals['_CACHESETRESPONSE']._serialized_end=231
  _globals['_CACHESERVICE']._serialized_start=234
  _globals['_CACHESERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
