# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import load_balancer_pb2 as load__balancer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in load_balancer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCachedData = channel.unary_unary(
                '/cache.CacheService/GetCachedData',
                request_serializer=load__balancer__pb2.CacheRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.CacheResponse.FromString,
                _registered_method=True)
        self.SetCachedData = channel.unary_unary(
                '/cache.CacheService/SetCachedData',
                request_serializer=load__balancer__pb2.CacheSetRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.CacheSetResponse.FromString,
                _registered_method=True)


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCachedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCachedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCachedData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCachedData,
                    request_deserializer=load__balancer__pb2.CacheRequest.FromString,
                    response_serializer=load__balancer__pb2.CacheResponse.SerializeToString,
            ),
            'SetCachedData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCachedData,
                    request_deserializer=load__balancer__pb2.CacheSetRequest.FromString,
                    response_serializer=load__balancer__pb2.CacheSetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cache.CacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCachedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cache.CacheService/GetCachedData',
            load__balancer__pb2.CacheRequest.SerializeToString,
            load__balancer__pb2.CacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCachedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cache.CacheService/SetCachedData',
            load__balancer__pb2.CacheSetRequest.SerializeToString,
            load__balancer__pb2.CacheSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
