# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import metadata_cache_channel_pb2 as metadata__cache__channel__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in metadata_cache_channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessQuery = channel.unary_unary(
                '/metadata_cache.MetadataService/ProcessQuery',
                request_serializer=metadata__cache__channel__pb2.QueryRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.RegisterServer = channel.unary_unary(
                '/metadata_cache.MetadataService/RegisterServer',
                request_serializer=metadata__cache__channel__pb2.RegisterRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.NotifyPromotion = channel.unary_unary(
                '/metadata_cache.MetadataService/NotifyPromotion',
                request_serializer=metadata__cache__channel__pb2.NotifyPromotionRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.NotifyPromotionResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPromotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=metadata__cache__channel__pb2.QueryRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.QueryResponse.SerializeToString,
            ),
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=metadata__cache__channel__pb2.RegisterRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.RegisterResponse.SerializeToString,
            ),
            'NotifyPromotion': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPromotion,
                    request_deserializer=metadata__cache__channel__pb2.NotifyPromotionRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.NotifyPromotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata_cache.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metadata_cache.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.MetadataService/ProcessQuery',
            metadata__cache__channel__pb2.QueryRequest.SerializeToString,
            metadata__cache__channel__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.MetadataService/RegisterServer',
            metadata__cache__channel__pb2.RegisterRequest.SerializeToString,
            metadata__cache__channel__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyPromotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.MetadataService/NotifyPromotion',
            metadata__cache__channel__pb2.NotifyPromotionRequest.SerializeToString,
            metadata__cache__channel__pb2.NotifyPromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResult = channel.unary_unary(
                '/metadata_cache.CacheService/GetResult',
                request_serializer=metadata__cache__channel__pb2.CacheRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.CacheResponse.FromString,
                _registered_method=True)
        self.SetResult = channel.unary_unary(
                '/metadata_cache.CacheService/SetResult',
                request_serializer=metadata__cache__channel__pb2.CacheSetRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.CacheSetResponse.FromString,
                _registered_method=True)
        self.GetLoad = channel.unary_unary(
                '/metadata_cache.CacheService/GetLoad',
                request_serializer=metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.LoadResponse.FromString,
                _registered_method=True)
        self.GetRole = channel.unary_unary(
                '/metadata_cache.CacheService/GetRole',
                request_serializer=metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.RoleResponse.FromString,
                _registered_method=True)
        self.PromoteToPrimary = channel.unary_unary(
                '/metadata_cache.CacheService/PromoteToPrimary',
                request_serializer=metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.PromotionResponse.FromString,
                _registered_method=True)
        self.RegisterReplica = channel.unary_unary(
                '/metadata_cache.CacheService/RegisterReplica',
                request_serializer=metadata__cache__channel__pb2.ReplicaRegisterRequest.SerializeToString,
                response_deserializer=metadata__cache__channel__pb2.ReplicaRegisterResponse.FromString,
                _registered_method=True)


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteToPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=metadata__cache__channel__pb2.CacheRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.CacheResponse.SerializeToString,
            ),
            'SetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SetResult,
                    request_deserializer=metadata__cache__channel__pb2.CacheSetRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.CacheSetResponse.SerializeToString,
            ),
            'GetLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoad,
                    request_deserializer=metadata__cache__channel__pb2.EmptyRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.LoadResponse.SerializeToString,
            ),
            'GetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRole,
                    request_deserializer=metadata__cache__channel__pb2.EmptyRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.RoleResponse.SerializeToString,
            ),
            'PromoteToPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteToPrimary,
                    request_deserializer=metadata__cache__channel__pb2.EmptyRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.PromotionResponse.SerializeToString,
            ),
            'RegisterReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterReplica,
                    request_deserializer=metadata__cache__channel__pb2.ReplicaRegisterRequest.FromString,
                    response_serializer=metadata__cache__channel__pb2.ReplicaRegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata_cache.CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metadata_cache.CacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/GetResult',
            metadata__cache__channel__pb2.CacheRequest.SerializeToString,
            metadata__cache__channel__pb2.CacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/SetResult',
            metadata__cache__channel__pb2.CacheSetRequest.SerializeToString,
            metadata__cache__channel__pb2.CacheSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/GetLoad',
            metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
            metadata__cache__channel__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/GetRole',
            metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
            metadata__cache__channel__pb2.RoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteToPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/PromoteToPrimary',
            metadata__cache__channel__pb2.EmptyRequest.SerializeToString,
            metadata__cache__channel__pb2.PromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_cache.CacheService/RegisterReplica',
            metadata__cache__channel__pb2.ReplicaRegisterRequest.SerializeToString,
            metadata__cache__channel__pb2.ReplicaRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
