# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentinel.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sentinel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esentinel.proto\x12\x08sentinel\"U\n\x1e\x43\x61\x63heServerRegistrationRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\\\n\x1f\x43\x61\x63heServerRegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nis_primary\x18\x02 \x01(\x08\x12\x14\n\x0cprimary_port\x18\x03 \x01(\x05\".\n\x18PrimaryForClusterRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\"K\n\x19PrimaryForClusterResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x11\n\tserver_id\x18\x02 \x01(\x05\x12\x0c\n\x04port\x18\x03 \x01(\x05\"5\n\x12HealthCheckRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\"B\n\x19GetClusterReplicasRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\"V\n\x1aGetClusterReplicasResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\'\n\x08replicas\x18\x02 \x03(\x0b\x32\x15.sentinel.ReplicaInfo\".\n\x0bReplicaInfo\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\x86\x03\n\x0fSentinelService\x12\x65\n\x0eRegisterServer\x12(.sentinel.CacheServerRegistrationRequest\x1a).sentinel.CacheServerRegistrationResponse\x12_\n\x14GetPrimaryForCluster\x12\".sentinel.PrimaryForClusterRequest\x1a#.sentinel.PrimaryForClusterResponse\x12J\n\x0bHealthCheck\x12\x1c.sentinel.HealthCheckRequest\x1a\x1d.sentinel.HealthCheckResponse\x12_\n\x12GetClusterReplicas\x12#.sentinel.GetClusterReplicasRequest\x1a$.sentinel.GetClusterReplicasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentinel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CACHESERVERREGISTRATIONREQUEST']._serialized_start=28
  _globals['_CACHESERVERREGISTRATIONREQUEST']._serialized_end=113
  _globals['_CACHESERVERREGISTRATIONRESPONSE']._serialized_start=115
  _globals['_CACHESERVERREGISTRATIONRESPONSE']._serialized_end=207
  _globals['_PRIMARYFORCLUSTERREQUEST']._serialized_start=209
  _globals['_PRIMARYFORCLUSTERREQUEST']._serialized_end=255
  _globals['_PRIMARYFORCLUSTERRESPONSE']._serialized_start=257
  _globals['_PRIMARYFORCLUSTERRESPONSE']._serialized_end=332
  _globals['_HEALTHCHECKREQUEST']._serialized_start=334
  _globals['_HEALTHCHECKREQUEST']._serialized_end=387
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=389
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=427
  _globals['_GETCLUSTERREPLICASREQUEST']._serialized_start=429
  _globals['_GETCLUSTERREPLICASREQUEST']._serialized_end=495
  _globals['_GETCLUSTERREPLICASRESPONSE']._serialized_start=497
  _globals['_GETCLUSTERREPLICASRESPONSE']._serialized_end=583
  _globals['_REPLICAINFO']._serialized_start=585
  _globals['_REPLICAINFO']._serialized_end=631
  _globals['_SENTINELSERVICE']._serialized_start=634
  _globals['_SENTINELSERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
