# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentinelServiceStub(object):
    """Sentinel service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterServer = channel.unary_unary(
                '/sentinel.SentinelService/RegisterServer',
                request_serializer=sentinel__pb2.CacheServerRegistrationRequest.SerializeToString,
                response_deserializer=sentinel__pb2.CacheServerRegistrationResponse.FromString,
                _registered_method=True)
        self.GetPrimaryForCluster = channel.unary_unary(
                '/sentinel.SentinelService/GetPrimaryForCluster',
                request_serializer=sentinel__pb2.PrimaryForClusterRequest.SerializeToString,
                response_deserializer=sentinel__pb2.PrimaryForClusterResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sentinel.SentinelService/HealthCheck',
                request_serializer=sentinel__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=sentinel__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SentinelServiceServicer(object):
    """Sentinel service definition
    """

    def RegisterServer(self, request, context):
        """Called by a cache server to register itself
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimaryForCluster(self, request, context):
        """Called by a replica to find the current primary of its cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Add this to the SentinelService
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentinelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=sentinel__pb2.CacheServerRegistrationRequest.FromString,
                    response_serializer=sentinel__pb2.CacheServerRegistrationResponse.SerializeToString,
            ),
            'GetPrimaryForCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimaryForCluster,
                    request_deserializer=sentinel__pb2.PrimaryForClusterRequest.FromString,
                    response_serializer=sentinel__pb2.PrimaryForClusterResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sentinel__pb2.HealthCheckRequest.FromString,
                    response_serializer=sentinel__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.SentinelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.SentinelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentinelService(object):
    """Sentinel service definition
    """

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelService/RegisterServer',
            sentinel__pb2.CacheServerRegistrationRequest.SerializeToString,
            sentinel__pb2.CacheServerRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimaryForCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelService/GetPrimaryForCluster',
            sentinel__pb2.PrimaryForClusterRequest.SerializeToString,
            sentinel__pb2.PrimaryForClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelService/HealthCheck',
            sentinel__pb2.HealthCheckRequest.SerializeToString,
            sentinel__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
